blueprint:
  name: "Room – Motion lights/switch + auto off + optional safety (multi-sensor)"
  description: >
    v1.1.1

    - AUTO ON: když je jakékoli motion čidlo ON -> zapne ovládaná zařízení
      (volitelně pouze pokud manual = off)
    - AUTO OFF: když jsou všechna motion čidla OFF po off_delay -> vypne ovládaná zařízení
      (volitelně pouze pokud manual = off)
    - SAFETY (pojistka): pokud manual = on a všechna čidla jsou OFF po safety_time -> vypne ovládaná zařízení a nastaví manual = off
      (volitelně zap/vyp)
    - Podpora více čidel (ANY ON pro rozsvícení, ALL OFF pro zhasnutí)
    - Ovládání light i switch (např. Shelly jako switch.*)
    - Volitelný jas (jen pro light; nepoužívej, pokud v cílech máš switch)

  domain: automation

  input:
    motion_sensors:
      name: Pohybová čidla (occupancy) – jedno nebo více
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    controlled_targets:
      name: Ovládaná zařízení (světla nebo spínače)
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    # --- Volitelný MANUAL režim (můžeš ignorovat)
    use_manual_condition:
      name: Použít podmínku manuálního režimu (manual=off)?
      default: true
      selector:
        boolean:

    manual_boolean:
      name: Input boolean – manuální režim (použije se jen když je volba výše zapnutá / nebo pro safety)
      selector:
        entity:
          domain: input_boolean

    # --- Volitelný JAS (jen pro light)
    use_brightness:
      name: Použít jas při AUTO ON (POUZE pokud ovládáš jen light)?
      default: false
      selector:
        boolean:

    auto_brightness:
      name: Jas pro AUTO ON (1–255)
      default: 204
      selector:
        number:
          min: 1
          max: 255
          mode: slider

    off_delay:
      name: Zpoždění vypnutí po ALL motion OFF
      default: "00:00:30"
      selector:
        duration:

    # --- Volitelná pojistka
    safety_enabled:
      name: Zapnout pojistku (safety)?
      default: true
      selector:
        boolean:

    safety_time:
      name: Pojistka – vypnutí po době bez pohybu (jen když manual=on)
      default: "00:30:00"
      selector:
        duration:

mode: restart

variables:
  motion_entities: !input motion_sensors
  manual_entity: !input manual_boolean
  use_manual: !input use_manual_condition
  use_bri: !input use_brightness
  safety_en: !input safety_enabled

  # ANY ON = rozsvítit
  any_motion_on: >
    {{ expand(motion_entities) | selectattr('state','eq','on') | list | count > 0 }}

  # ALL OFF = zhasínat
  all_motion_off: >
    {{ expand(motion_entities) | selectattr('state','eq','off') | list | count == (expand(motion_entities) | list | count) }}

  manual_is_off: >
    {{ is_state(manual_entity, 'off') }}

  manual_is_on: >
    {{ is_state(manual_entity, 'on') }}

trigger:
  # Rozsvítit, když je jakékoli čidlo ON
  - id: motion_on
    platform: template
    value_template: "{{ any_motion_on }}"

  # Zhasnout, když jsou všechna čidla OFF po off_delay
  - id: motion_off
    platform: template
    value_template: "{{ all_motion_off }}"
    for: !input off_delay

  # Pojistka, když jsou všechna čidla OFF po safety_time
  - id: safety_off
    platform: template
    value_template: "{{ all_motion_off }}"
    for: !input safety_time

action:
  - choose:

      # --- AUTO ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_on' }}"
          # volitelná podmínka manual=off
          - condition: template
            value_template: "{{ (not use_manual) or manual_is_off }}"
        sequence:
          - choose:
              # pokud chceš jas (jen pro light)
              - conditions:
                  - condition: template
                    value_template: "{{ use_bri }}"
                sequence:
                  - service: light.turn_on
                    target: !input controlled_targets
                    data:
                      brightness: !input auto_brightness
            default:
              - service: homeassistant.turn_on
                target: !input controlled_targets

      # --- AUTO OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_off' }}"
          # volitelná podmínka manual=off
          - condition: template
            value_template: "{{ (not use_manual) or manual_is_off }}"
          # pojistka proti falešnému odpalu: opravdu pořád ALL OFF
          - condition: template
            value_template: "{{ all_motion_off }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input controlled_targets

      # --- SAFETY (manual=on + dlouho bez pohybu)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'safety_off' }}"
          - condition: template
            value_template: "{{ safety_en and manual_is_on and all_motion_off }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input controlled_targets
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_boolean
