blueprint:
  name: "Room – Motion lights + auto off + safety"
  description: >
    v1.0.5 - auto ON závisí jen na manual OFF (neřeší stav skupiny)
    + safety pouze když manual ON: po safety_time bez pohybu zhasne skupinu a vypne manual.

    - motion ON + manual OFF -> rozsvítí auto_lights na daný jas
    - motion OFF po off_delay + manual OFF -> zhasne auto_lights
    - motion OFF po safety_time + manual ON -> zhasne light_group + vypne manual
  domain: automation

  input:
    motion_sensor:
      name: Pohybové čidlo (occupancy)
      selector:
        entity:
          domain: binary_sensor

    manual_boolean:
      name: Input boolean - manuální režim
      selector:
        entity:
          domain: input_boolean

    light_group:
      name: Skupina světel (hlavní)
      selector:
        entity:
          domain: light

    auto_lights:
      name: Světla pro automatiku (např. 5+1)
      selector:
        target:
          entity:
            domain: light

    auto_brightness:
      name: Jas pro auto světla při pohybu (0-255)
      default: 204
      selector:
        number:
          min: 1
          max: 255
          mode: slider

    off_delay:
      name: Zpoždění vypnutí po motion OFF
      default: "00:00:30"
      selector:
        duration:

    safety_time:
      name: Pojistka vypnutí po době bez pohybu (jen když manual ON)
      default: "00:30:00"
      selector:
        duration:

mode: restart

trigger:
  - id: motion_on
    platform: state
    entity_id: !input motion_sensor
    to: "on"

  - id: motion_off
    platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input off_delay

  - id: safety_off
    platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input safety_time

action:
  - choose:
      # AUTO ON: jen manual OFF, stav skupiny se neřeší
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_on' }}"
          - condition: state
            entity_id: !input manual_boolean
            state: "off"
        sequence:
          - service: light.turn_on
            target: !input auto_lights
            data:
              brightness: !input auto_brightness

      # AUTO OFF: motion OFF po off_delay + manual OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_off' }}"
          - condition: state
            entity_id: !input manual_boolean
            state: "off"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - service: light.turn_off
            target: !input auto_lights

      # SAFETY: jen když manual ON + stále bez pohybu -> zhasni skupinu + vypni manual
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'safety_off' }}"
          - condition: state
            entity_id: !input manual_boolean
            state: "on"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_group
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_boolean
