blueprint:
  name: "Room – Motion (multi) + Auto OFF + Optional Manual + Optional Safety (lights+switches)"
  description: >
    v2.1.0

    - Motion ON (any sensor) -> turn ON auto targets.
    - Motion goes to no-motion (all sensors off) -> after off_delay -> turn OFF auto targets.
    - Optional: manual condition (auto runs only when manual_boolean is OFF).
    - Optional: safety (if manual is ON and all sensors off for safety_time -> turn OFF safety targets + manual OFF).
    - Supports light entities (with optional brightness) and switch entities (on/off only).
  domain: automation

  input:
    motion_sensors:
      name: Pohybová čidla (1 nebo více)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    use_manual_condition:
      name: Použít podmínku manuálního režimu (auto běží jen když manual=OFF)
      default: true
      selector:
        boolean:

    manual_boolean:
      name: Input boolean - manuální režim
      selector:
        entity:
          domain: input_boolean

    light_targets:
      name: Auto - světla (light.*)
      default: {}
      selector:
        target:
          entity:
            domain: light

    use_brightness:
      name: Použít jas pro auto světla
      default: true
      selector:
        boolean:

    auto_brightness:
      name: Jas pro auto světla při pohybu (0-255)
      default: 204
      selector:
        number:
          min: 1
          max: 255
          mode: slider

    switch_targets:
      name: Auto - spínače (switch.*, např. Shelly)
      default: {}
      selector:
        target:
          entity:
            domain: switch

    off_delay:
      name: Zpoždění vypnutí po době bez pohybu
      default: "00:00:30"
      selector:
        duration:

    use_safety:
      name: Zapnout pojistku (safety)
      default: true
      selector:
        boolean:

    safety_time:
      name: Pojistka - doba bez pohybu (jen když manual=ON)
      default: "00:30:00"
      selector:
        duration:

    safety_light_targets:
      name: Pojistka - světla k vypnutí (např. všechno v místnosti)
      default: {}
      selector:
        target:
          entity:
            domain: light

    safety_switch_targets:
      name: Pojistka - spínače k vypnutí (např. všechno v místnosti)
      default: {}
      selector:
        target:
          entity:
            domain: switch

mode: restart

variables:
  motion_sensors: !input motion_sensors
  use_manual_condition: !input use_manual_condition
  manual_boolean: !input manual_boolean
  light_targets: !input light_targets
  switch_targets: !input switch_targets
  use_brightness: !input use_brightness
  auto_brightness: !input auto_brightness
  off_delay: !input off_delay
  use_safety: !input use_safety
  safety_time: !input safety_time
  safety_light_targets: !input safety_light_targets
  safety_switch_targets: !input safety_switch_targets

  any_motion_on: >-
    {{ expand(motion_sensors) | selectattr('state','eq','on') | list | count > 0 }}
  all_motion_off: >-
    {{ expand(motion_sensors) | selectattr('state','eq','on') | list | count == 0 }}

trigger:
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  # re-řešíme zhasnutí / pojistku kdykoliv nějaké čidlo přejde na off
  - id: motion_changed_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

action:
  - choose:
      # ========== AUTO ON ==========
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_on' }}"
          - condition: template
            value_template: >
              {{ (not use_manual_condition) or is_state(manual_boolean, 'off') }}
        sequence:
          # lights ON
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ light_targets.entity_id is defined and (light_targets.entity_id | count > 0) }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ use_brightness }}"
                        sequence:
                          - service: light.turn_on
                            target: !input light_targets
                            data:
                              brightness: !input auto_brightness
                      - conditions:
                          - condition: template
                            value_template: "{{ not use_brightness }}"
                        sequence:
                          - service: light.turn_on
                            target: !input light_targets
            default: []
          # switches ON
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ switch_targets.entity_id is defined and (switch_targets.entity_id | count > 0) }}"
                sequence:
                  - service: switch.turn_on
                    target: !input switch_targets
            default: []

      # ========== AUTO OFF ==========
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_changed_off' }}"
          - condition: template
            value_template: >
              {{ (not use_manual_condition) or is_state(manual_boolean, 'off') }}
        sequence:
          # čekáme off_delay a pak ověříme, že pořád není pohyb
          - delay: !input off_delay
          - condition: template
            value_template: "{{ all_motion_off }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ light_targets.entity_id is defined and (light_targets.entity_id | count > 0) }}"
                sequence:
                  - service: light.turn_off
                    target: !input light_targets
            default: []
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ switch_targets.entity_id is defined and (switch_targets.entity_id | count > 0) }}"
                sequence:
                  - service: switch.turn_off
                    target: !input switch_targets
            default: []

      # ========== SAFETY ==========
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_changed_off' }}"
          - condition: template
            value_template: "{{ use_safety }}"
          - condition: state
            entity_id: !input manual_boolean
            state: "on"
        sequence:
          - delay: !input safety_time
          - condition: state
            entity_id: !input manual_boolean
            state: "on"
          - condition: template
            value_template: "{{ all_motion_off }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ safety_light_targets.entity_id is defined and (safety_light_targets.entity_id | count > 0) }}"
                sequence:
                  - service: light.turn_off
                    target: !input safety_light_targets
            default: []
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ safety_switch_targets.entity_id is defined and (safety_switch_targets.entity_id | count > 0) }}"
                sequence:
                  - service: switch.turn_off
                    target: !input safety_switch_targets
            default: []
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_boolean
