blueprint:
  name: "Room – Motion (multi) + Auto OFF + Optional Manual + Optional Safety (lights+switches)"
  description: >
    v2.0.2

    - Motion ON (any sensor) -> turn ON auto targets.
    - Motion OFF (all sensors off for off_delay) -> turn OFF auto targets.
    - Optional: manual condition (auto runs only when manual_boolean is OFF).
    - Optional: safety (if manual is ON and all sensors off for safety_time -> turn OFF safety targets + manual OFF).
    - Supports light entities (with optional brightness) and switch entities (on/off only).
  domain: automation

  input:
    motion_sensors:
      name: Pohybová čidla (1 nebo více)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    use_manual_condition:
      name: Použít podmínku manuálního režimu
      default: true
      selector:
        boolean:

    manual_boolean:
      name: Input boolean - manuální režim
      selector:
        entity:
          domain: input_boolean

    light_targets:
      name: Auto - světla (light.*)
      default: {}
      selector:
        target:
          entity:
            domain: light

    use_brightness:
      name: Použít jas pro auto světla
      default: true
      selector:
        boolean:

    auto_brightness:
      name: Jas pro auto světla při pohybu (0-255)
      default: 204
      selector:
        number:
          min: 1
          max: 255
          mode: slider

    switch_targets:
      name: Auto - spínače (switch.*, např. Shelly)
      default: {}
      selector:
        target:
          entity:
            domain: switch

    off_delay:
      name: Zpoždění vypnutí po všech čidlech OFF
      default: "00:00:30"
      selector:
        duration:

    use_safety:
      name: Zapnout pojistku (safety)
      default: true
      selector:
        boolean:

    safety_time:
      name: Pojistka - doba bez pohybu (jen když manual=ON)
      default: "00:30:00"
      selector:
        duration:

    safety_light_targets:
      name: Pojistka - světla k vypnutí (např. všechno v místnosti)
      default: {}
      selector:
        target:
          entity:
            domain: light

    safety_switch_targets:
      name: Pojistka - spínače k vypnutí
      default: {}
      selector:
        target:
          entity:
            domain: switch

mode: restart

trigger:
  # ANY sensor ON
  - id: motion_any_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  # ALL sensors OFF for off_delay
  - id: motion_all_off
    platform: template
    value_template: >
      {{ expand(!input motion_sensors)
         | selectattr('state','eq','on')
         | list
         | count == 0 }}
    for: !input off_delay

  # SAFETY: ALL sensors OFF for safety_time (only evaluated; we still gate by use_safety + manual in actions)
  - id: safety_all_off
    platform: template
    value_template: >
      {{ expand(!input motion_sensors)
         | selectattr('state','eq','on')
         | list
         | count == 0 }}
    for: !input safety_time

action:
  - choose:
      # ========== AUTO ON ==========
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_any_on' }}"
          - condition: template
            value_template: >
              {% set use_manual = !input use_manual_condition %}
              {% if use_manual %}
                {{ is_state(!input manual_boolean, 'off') }}
              {% else %}
                true
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (!input light_targets).get('entity_id') is defined and
                         (( !input light_targets ).get('entity_id') | count > 0) }}
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ !input use_brightness }}"
                        sequence:
                          - service: light.turn_on
                            target: !input light_targets
                            data:
                              brightness: !input auto_brightness
                      - conditions:
                          - condition: template
                            value_template: "{{ not (!input use_brightness) }}"
                        sequence:
                          - service: light.turn_on
                            target: !input light_targets
            default: []
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (!input switch_targets).get('entity_id') is defined and
                         (( !input switch_targets ).get('entity_id') | count > 0) }}
                sequence:
                  - service: switch.turn_on
                    target: !input switch_targets
            default: []

      # ========== AUTO OFF ==========
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_all_off' }}"
          - condition: template
            value_template: >
              {% set use_manual = !input use_manual_condition %}
              {% if use_manual %}
                {{ is_state(!input manual_boolean, 'off') }}
              {% else %}
                true
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (!input light_targets).get('entity_id') is defined and
                         (( !input light_targets ).get('entity_id') | count > 0) }}
                sequence:
                  - service: light.turn_off
                    target: !input light_targets
            default: []
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (!input switch_targets).get('entity_id') is defined and
                         (( !input switch_targets ).get('entity_id') | count > 0) }}
                sequence:
                  - service: switch.turn_off
                    target: !input switch_targets
            default: []

      # ========== SAFETY (manual ON -> after safety_time with no motion) ==========
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'safety_all_off' }}"
          - condition: template
            value_template: "{{ !input use_safety }}"
          - condition: state
            entity_id: !input manual_boolean
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (!input safety_light_targets).get('entity_id') is defined and
                         (( !input safety_light_targets ).get('entity_id') | count > 0) }}
                sequence:
                  - service: light.turn_off
                    target: !input safety_light_targets
            default: []
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (!input safety_switch_targets).get('entity_id') is defined and
                         (( !input safety_switch_targets ).get('entity_id') | count > 0) }}
                sequence:
                  - service: switch.turn_off
                    target: !input safety_switch_targets
            default: []
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_boolean
