blueprint:
  name: "Room – Motion (multi) + optional manual gate + optional safety + lights/switches"
  description: >
    v2.0.0

    - AUTO ON: když je jakékoliv motion ON -> zapne auto_targets
      (volitelně jen když manual_boolean = off)
      (volitelně nastaví jas pouze pro light entity)

    - AUTO OFF: když jsou všechna motion OFF po off_delay -> vypne auto_targets
      (volitelně jen když manual_boolean = off)

    - SAFETY (volitelně): když jsou všechna motion OFF po safety_time a manual_boolean = on
      -> vypne safety_targets (může být "vše v místnosti") + nastaví manual_boolean = off

  domain: automation

  input:
    motion_sensors:
      name: Pohybová čidla (1 nebo více)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    manual_boolean:
      name: Input boolean - manuální režim
      selector:
        entity:
          domain: input_boolean

    use_manual_gate:
      name: Použít podmínku manuálního režimu pro AUTO (ON/OFF)
      description: Když zapnuto, AUTO ON/OFF běží jen pokud manual_boolean je OFF.
      default: true
      selector:
        boolean:

    auto_targets:
      name: Cíle automatického zapnutí/vypnutí (light i switch)
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    use_brightness:
      name: Použít jas při AUTO ON (pouze pro světla)
      default: true
      selector:
        boolean:

    auto_brightness:
      name: Jas pro AUTO ON (1-255)
      default: 204
      selector:
        number:
          min: 1
          max: 255
          mode: slider

    off_delay:
      name: Zpoždění vypnutí po všech motion OFF
      default: "00:00:30"
      selector:
        duration:

    enable_safety:
      name: Povolit pojistku (SAFETY)
      default: true
      selector:
        boolean:

    safety_time:
      name: Pojistka vypnutí po době bez pohybu (všechna čidla OFF)
      default: "00:30:00"
      selector:
        duration:

    safety_targets:
      name: Cíle pojistky (např. všechna světla v místnosti)
      description: Tohle se vypne při SAFETY (a manual se přepne na OFF).
      selector:
        target:
          entity:
            domain:
              - light
              - switch

mode: restart

trigger:
  # jakékoliv čidlo ON
  - id: motion_any_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  # všechna čidla OFF po off_delay
  - id: motion_all_off_delay
    platform: template
    value_template: >
      {% set sensors = expand(!input motion_sensors) %}
      {{ sensors | count > 0 and (sensors | selectattr('state','eq','on') | list | length == 0) }}
    for: !input off_delay

  # všechna čidla OFF po safety_time
  - id: safety_all_off
    platform: template
    value_template: >
      {% set sensors = expand(!input motion_sensors) %}
      {{ sensors | count > 0 and (sensors | selectattr('state','eq','on') | list | length == 0) }}
    for: !input safety_time

action:
  - variables:
      manual_ent: !input manual_boolean
      manual_gate: !input use_manual_gate
      do_bri: !input use_brightness
      bri: !input auto_brightness
      safety_enabled: !input enable_safety

  - choose:

      # ===== AUTO ON =====
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_any_on' }}"
          - condition: template
            value_template: >
              {{ (not manual_gate) or (is_state(manual_ent, 'off')) }}
        sequence:
          # nejdřív světla s jasem (pokud povoleno)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ do_bri }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: >
                        {% set t = expand(!input auto_targets.entity_id) %}
                        {{ t | selectattr('domain','eq','light') | map(attribute='entity_id') | list }}
                    data:
                      brightness: "{{ bri }}"
                  - service: homeassistant.turn_on
                    target:
                      entity_id: >
                        {% set t = expand(!input auto_targets.entity_id) %}
                        {{ t | rejectattr('domain','eq','light') | map(attribute='entity_id') | list }}
            default:
              - service: homeassistant.turn_on
                target: !input auto_targets

      # ===== AUTO OFF =====
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_all_off_delay' }}"
          - condition: template
            value_template: >
              {{ (not manual_gate) or (is_state(manual_ent, 'off')) }}
        sequence:
          - service: homeassistant.turn_off
            target: !input auto_targets

      # ===== SAFETY =====
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'safety_all_off' }}"
          - condition: template
            value_template: "{{ safety_enabled }}"
          - condition: state
            entity_id: !input manual_boolean
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target: !input safety_targets
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_boolean
