blueprint:
  name: Room – Switch → Lights (manual mode)
  description: >
    Ovládání skupiny světel přes Hue Dimmer v2 (Zigbee2MQTT MQTT topic).
    on_press: když manual OFF -> rozsvítí a nastaví manual ON, když manual ON -> zhasne a nastaví manual OFF.
    up/down: zvyšuje/snižuje jas a nastaví manual ON.
  domain: automation
  input:
    mqtt_action_topic:
      name: MQTT topic (…/action)
      selector:
        text:
    manual_boolean:
      name: Input boolean - manuální režim
      selector:
        entity:
          domain: input_boolean
    light_group:
      name: Skupina světel (light entity)
      selector:
        entity:
          domain: light
    on_brightness_pct:
      name: Jas při zapnutí (on_press když manual OFF)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: "%"
    step:
      name: Krok jasu pro up/down
      default: 40
      selector:
        number:
          min: 1
          max: 100
          mode: slider

mode: single

trigger:
  - platform: mqtt
    topic: !input mqtt_action_topic

variables:
  action: "{{ trigger.payload }}"
  manual: !input manual_boolean
  group: !input light_group
  step: !input step
  on_pct: !input on_brightness_pct

action:
  - choose:
      - conditions: "{{ action == 'on_press' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input manual_boolean
                    state: "off"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_group
                    data:
                      brightness_pct: !input on_brightness_pct
                  - service: input_boolean.turn_on
                    target:
                      entity_id: !input manual_boolean
              - conditions:
                  - condition: state
                    entity_id: !input manual_boolean
                    state: "on"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input light_group
                  - service: input_boolean.turn_off
                    target:
                      entity_id: !input manual_boolean

      - conditions: "{{ action == 'up_press' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_boolean
          - service: light.turn_on
            target:
              entity_id: !input light_group
            data:
              brightness_step: "{{ step | int }}"

      - conditions: "{{ action == 'down_press' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_boolean
          - service: light.turn_on
            target:
              entity_id: !input light_group
            data:
              brightness_step: "{{ (step | int) * -1 }}"
